export const TEMPLATES = [
  {
    id: 'default',
    name: 'Obsidian',
    description: 'Dark glass with orange fire',
    free: true,
    preview: {
      primary_color: '#F15025',
      font_family: 'Inter',
      border_radius: '14px',
      theme: 'dark',
    },
  },
  {
    id: 'minimal',
    name: 'Chalk',
    description: 'Pure white on pitch black',
    free: true,
    preview: {
      primary_color: '#E8E8E8',
      font_family: 'Inter',
      border_radius: '4px',
      theme: 'dark',
    },
  },
  {
    id: 'soft',
    name: 'Dusk',
    description: 'Muted violet, easy on eyes',
    free: true,
    preview: {
      primary_color: '#9d7fea',
      font_family: 'Inter',
      border_radius: '18px',
      theme: 'dark',
    },
  },
  {
    id: 'neon',
    name: 'Matrix',
    description: 'Terminal green on deep black',
    free: false,
    preview: {
      primary_color: '#00ff87',
      font_family: 'JetBrains Mono',
      border_radius: '4px',
      theme: 'dark',
    },
  },
  {
    id: 'corporate',
    name: 'Slate',
    description: 'Confident blue for enterprise',
    free: false,
    preview: {
      primary_color: '#4d9fff',
      font_family: 'Inter',
      border_radius: '8px',
      theme: 'dark',
    },
  },
  {
    id: 'warm',
    name: 'Ember',
    description: 'Deep amber glow',
    free: false,
    preview: {
      primary_color: '#ff9500',
      font_family: 'Inter',
      border_radius: '10px',
      theme: 'dark',
    },
  },
  {
    id: 'ocean',
    name: 'Frost',
    description: 'Arctic cyan, crisp contrast',
    free: false,
    preview: {
      primary_color: '#00d4ff',
      font_family: 'Inter',
      border_radius: '12px',
      theme: 'dark',
    },
  },
  {
    id: 'rose',
    name: 'Sakura',
    description: 'Soft pink for consumer apps',
    free: false,
    preview: {
      primary_color: '#ff6eb4',
      font_family: 'Inter',
      border_radius: '20px',
      theme: 'dark',
    },
  },
]